### ISSUE TITLE
Influx write errors cause an excpetion

### ISSUE THREAD

**Issue by MClarkDev** [mikenye/docker-piaware-to-influx#10]
WHen the Influx write endpoint returns non 200, the script throws an exception:

```
  File "./piaware2influx.py", line 80, in send_line_protocol
    errormsg += "" + telegraf_request.status_code
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by MClarkDev** [comment]
PR: https://github.com/mikenye/docker-piaware-to-influx/pull/11

**Comment by mikenye** [comment]
Appreciate you taking the time to fix this, thanks. :-)

**Comment by mikenye** [comment]
FYI just built & pushed `latest`
